lens: {}
wreq: {}
warp: {}
packdeps: {}
syb: {}
# Deprecated in favour of network
network-bytestring:
  skip: true
HsOpenSSL:
  # https://github.com/phonohawk/HsOpenSSL/issues/36
  allow-newer: false
  apt-packages:
    - libssl-dev
libxml:
  extra-flags:
    - "--extra-include-dirs=/usr/include/libxml2"
  apt-packages:
    - libxml2-dev
tar:
  extra-flags:
    - "-f-old-time"
zlib:
  apt-packages:
    - zlib1g-dev
pcre-light:
  apt-packages:
    - libpcre3-dev
