name: upper-bounds-builder
version: 0.1.0.0
synopsis: Upper bounds builder
description: Upper bounds builder for hackage packages
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/upper-bounds-builder
category: Text
extra-source-files: README.md

ghc-options: -Wall

dependencies:
  - base >= 4.7 && <4.9
  - tar >=0.4 && <0.5
  - bytestring >=0.9
  - text >=0.7
  - aeson
  - yaml
  - transformers
  - split >= 0.1.2.3
  - time  >= 1.4
  - Cabal      >= 1.18
  - containers  >= 0.5
  - directory    >= 1.0
  - filepath     >= 1.1
  - pretty
  - bifunctors
  - binary
  - mtl
  - dlist
  - binary-orphans
  - binary-tagged
  - exceptions
  - path
  - shake
  - optparse-applicative

library:
  source-dirs: src

executables:
  upper-bounds-builder:
    source-dirs: cli
    main: Main.hs
    dependencies:
      - upper-bounds-builder
